In [33]:
%matplotlib inline

from matplotlib import pyplot as plt
import gym
from gym import wrappers
# from gym.wrappers import Monitor
import itertools
import numpy as np
import os
import random
import sys
import psutil
import tensorflow as tf
import logging
import datetime
from datetime import datetime

if "../" not in sys.path:
  sys.path.append("../")

# from lib import plotting
# from collections import deque, namedtuple
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG,
        format='%(asctime)s [%(levelname)s] %(message)s')

# Define the Keras TensorBoard callback.
logdir = "logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)


2022-06-07 21:14:39,377 [DEBUG] Loaded backend module://matplotlib_inline.backend_inline version unknown.


In [15]:
env_id = "ALE/Breakout-v5"
env = gym.make(id=env_id, render_mode="rgb_array", obs_type="grayscale")
env = gym.wrappers.RecordVideo(env,
                               './videos/games',
                               name_prefix="rl-video-1")
# env = gym.wrappers.RecordVideo(env, './videos/games')

In [8]:
print(env.observation_space.shape[0])
print(env.observation_space.shape[1])

210
160


In [7]:
print(np.zeros([1, 2]))

[[0. 0.]]


In [ ]:
class ReplayBuffer:
    
    def __init__(self):
        ...

In [ ]:
class DQNAgent:

    def __init__(self, env, input_shape, learning_rate=0.00025,
                 gamma=0.99, epsilon=1.0, epsilon_decrease_rate=9e-7, min_epsilon=0.1):
        '''
        Args:
            input_shape: shape of the input to the network
        '''
        # hyperparameters
        self.gamma = gamma
        self.learning_rate = learning_rate
        
        # image input parameters
        self.img_shape = ()
        
        # exploration parameters
        self.epsilon = epsilon
        self.epsilon_decrease_rate = epsilon_decrease_rate
        self.min_epsilon = min_epsilon
        
        # evaluation network
        self.evaluate_network = self.build_network()
        # target network
        self.target_network

    def build_network(self, input_shape, output_size, conv_activation=tf.nn.relu):
        model = tf.keras.models.Sequential()
        
        return model

    def get_next_state():
        ...

    def decide():
        ...

    def learn():
        ...

    def update_target_network():
        ...

    def save_network():
        ...


In [7]:
input_shape = (4, 110, 84)

print(input_shape[-1])
print(input_shape[-2])
print(input_shape[-3])


84
110
4


In [4]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [11]:
print(env.action_space.n)

4


In [16]:
print(env.observation_space.shape)

(210, 160)


In [17]:
x = env.observation_space.shape
x

(210, 160)

In [31]:
logging.info("abc")

2022-06-07 20:26:37,522 [INFO] abc


In [34]:
print(itertools.count())

count(0)


In [3]:
import gym

env = gym.make('BreakoutNoFrameskip-v4')
observation = env.reset()
while True:
    print(env.render(mode='rgb_array'))
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        break
env.close()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


In [4]:
i = 1

In [5]:
i

1