In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

logdir = 'logs/scalars'
file_writer = tf.summary.create_file_writer(logdir + "/test1")
file_writer.set_as_default()

%tensorboard --logdir=logs/scalars

UsageError: Line magic function `%tensorboard` not found.


In [22]:
x = np.linspace(-1,1,100)
y = x ** 2

for i in range(100):
    tf.summary.scalar('x', y[i], step=i)

In [26]:
inputs = keras.Input(shape=(1,))
l = layers.Dense(1, activation='linear')(inputs)
model = keras.Model(inputs=inputs, outputs=l)

optimizer = tf.optimizers.Adam(learning_rate=0.01)

def update(x, y):
    with tf.GradientTape() as tape:
        loss = (y - model(x)) ** 2
    
    grad = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grad, model.trainable_variables))
    
    return loss

for i in range(100):
    tf.summary.scalar('loss', update(x[i], y[i]), step=i)

ValueError: Exception encountered when calling layer "model_8" (type Functional).

Input 0 of layer "dense_10" is incompatible with the layer: expected min_ndim=2, found ndim=0. Full shape received: ()

Call arguments received:
  • inputs=[['tf.Tensor(shape=(), dtype=float64)']]
  • training=None
  • mask=None

In [20]:
print(x)
print(y)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[1.         0.60493827 0.30864198 0.11111111 0.01234568 0.01234568
 0.11111111 0.30864198 0.60493827 1.        ]


In [15]:
optimizer = tf.optimizers.Adam(learning_rate=0.01)
inputs = keras.Input(shape=(2,))
l = layers.Dense(1, activation='linear')(inputs)
model = keras.Model(inputs=inputs, outputs=l)
x = tf.Variable([[1.0, 2.0]])

with tf.GradientTape() as tape:
    y = model(x) ** 2

grad = tape.gradient(y, x)
print(grad)
zipped = zip(grad, x)
print(list(zipped))
optimizer.apply_gradients(zip(grad, model.trainable_variables))


tf.Tensor([[-3.6595562  3.584101 ]], shape=(1, 2), dtype=float32)
[(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-3.6595562,  3.584101 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>)]


InvalidArgumentError: var and grad do not have the same shape[2,1] [2] [Op:ResourceApplyAdam]

In [28]:

t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
s = [1, 2, 3, 4, 5]

for i in range(len(t)):
    tf.summary.scalar('t', t[i], step=i+1)
    print(t[i])
file_writer.close()

1
2
3
4
5
6
7
8
9
10


In [32]:
y_label = tf.convert_to_tensor([2], dtype=tf.int64)
y_hat = tf.convert_to_tensor([[1.0, 2.0, 3.0]], dtype=tf.float32)
c = tf.nn.sparse_softmax_cross_entropy_with_logits(
    logits=y_hat, labels=y_label)

print(c)


tf.Tensor([0.40760604], shape=(1,), dtype=float32)


In [35]:
print(-tf.math.log(0.6652))


tf.Tensor(0.40766755, shape=(), dtype=float32)


In [33]:
logits = tf.constant([[2., -5., .5, -.1],
                      [0., 0., 1.9, 1.4],
                      [-100., 100., -100., -100.]])
labels = tf.constant([0, 3, 1])
tf.nn.sparse_softmax_cross_entropy_with_logits(
    labels=labels, logits=logits).numpy()


array([0.2975074, 1.1448326, 0.       ], dtype=float32)

In [38]:
s = tf.math.softmax(logits, axis=1)[1].numpy()
print(s)

[0.07848619 0.07848619 0.5247504  0.3182772 ]


In [39]:
print(-tf.math.log(0.3182772))


tf.Tensor(1.1448326, shape=(), dtype=float32)


In [24]:
title_data = np.random.randint(2, size=(4))
print(title_data.shape)
print(title_data)



(4,)
[1 1 1 1]


In [17]:
# this is a logistic regression in Keras
x = keras.Input(shape=(2,))
y = layers.Dense(16, activation='softmax')(x)
model = keras.Model(x, y)

inp = [[1, 2]]
model(inp)

ValueError: Layer "model_8" expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>]

In [7]:
out = keras.Input(shape=(2,), name='out')
x = [1, 2]
x = x.numpy()
p = out(x)
print(p)

AttributeError: 'list' object has no attribute 'numpy'

In [3]:
s = tf.random.categorical([[-100000000000000., 2., 3.]], num_samples=10)
print(s)

tf.Tensor([[1 2 2 2 2 1 2 1 2 2]], shape=(1, 10), dtype=int64)


In [4]:
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]), 5)

print(tf.math.log([[0.5, 0.5]]))
print(samples)
print(samples[0, 0])

tf.Tensor([[-0.6931472 -0.6931472]], shape=(1, 2), dtype=float32)
tf.Tensor([[1 1 1 0 0]], shape=(1, 5), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)


In [6]:
inputs = keras.Input(shape=(32,)) 
x = layers.Dense(64, activation='relu')(inputs) 
outputs = layers.Dense(10)(x) 
mlp = keras.Model(inputs, outputs)

print(mlp.summary())

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 10)                650       
                                                                 
Total params: 2,762
Trainable params: 2,762
Non-trainable params: 0
_________________________________________________________________
None


In [4]:
class MLP(keras.Model):    
    def __init__(self, **kwargs):     
        super(MLP, self).__init__(**kwargs)     
        self.dense_1 = layers.Dense(64, activation='relu')     
        self.dense_2 = layers.Dense(10)    
    
    def call(self, inputs):     
        x = self.dense_1(inputs)     
        return self.dense_2(x)  # Instantiate the model. mlp = MLP() # Necessary to create the model's state. # The model doesn't have a state until it's called at least once. _ = mlp(tf.zeros((1, 32)))

In [5]:
mlp=MLP.call(Input(shape=(32,)))
mlp.build(input_shape=(None, 32))
mlp.summary()

Model: "mlp"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               multiple                  2112      
                                                                 
 dense_1 (Dense)             multiple                  650       
                                                                 
Total params: 2,762
Trainable params: 2,762
Non-trainable params: 0
_________________________________________________________________


In [25]:
num_tags = 12  # Number of unique issue tags
num_words = 10000  # Size of vocabulary obtained when preprocessing text data
num_departments = 4  # Number of departments for predictions

title_input = keras.Input(
    shape=(None,), name="title"
)  # Variable-length sequence of ints
body_input = keras.Input(shape=(None,), name="body")  # Variable-length sequence of ints
tags_input = keras.Input(
    shape=(num_tags,), name="tags"
)  # Binary vectors of size `num_tags`

# Embed each word in the title into a 64-dimensional vector
title_features = layers.Embedding(num_words, 64)(title_input)
# Embed each word in the text into a 64-dimensional vector
body_features = layers.Embedding(num_words, 64)(body_input)

# Reduce sequence of embedded words in the title into a single 128-dimensional vector
title_features = layers.LSTM(128)(title_features)
# Reduce sequence of embedded words in the body into a single 32-dimensional vector
body_features = layers.LSTM(32)(body_features)

# Merge all available features into a single large vector via concatenation
x = layers.concatenate([title_features, body_features, tags_input])

# Stick a logistic regression for priority prediction on top of the features
priority_pred = layers.Dense(1, name="priority")(x)
# Stick a department classifier on top of the features
department_pred = layers.Dense(num_departments, name="department")(x)

# Instantiate an end-to-end model predicting both priority and department
model = keras.Model(
    inputs=[title_input, body_input, tags_input],
    outputs=[priority_pred, department_pred],
)

print(model.summary())

Model: "model_9"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 title (InputLayer)             [(None, None)]       0           []                               
                                                                                                  
 body (InputLayer)              [(None, None)]       0           []                               
                                                                                                  
 embedding (Embedding)          (None, None, 64)     640000      ['title[0][0]']                  
                                                                                                  
 embedding_1 (Embedding)        (None, None, 64)     640000      ['body[0][0]']                   
                                                                                            

In [2]:
inputs = keras.Input(shape=(784,), name='digits')
common = layers.Dense(64, activation='relu')
actor = layers.Dense(1, activation='sigmoid')(common)
critic = layers.Dense(1)(common)

model = keras.Model(inputs=inputs, outputs=[actor, critic])

TypeError: Inputs to a layer should be tensors. Got: <keras.layers.core.dense.Dense object at 0x000001C702E94A90>

In [3]:
print(range(10))

for i in range(10):
  print(i)

range(0, 10)
0
1
2
3
4
5
6
7
8
9


In [12]:
x = tf.constant(3.0)
with tf.GradientTape() as tape:
  # tape.watch(x)
  y = x**2

# dy = 2x * dx
dy_dx = tape.gradient(y, x)
print(dy_dx.numpy())


AttributeError: 'NoneType' object has no attribute 'numpy'

In [8]:
s = tf.one_hot([0], depth=4)
s = tf.Variable(s)
with tf.GradientTape() as tape:
    tape.watch(s)
    loss = tf.reduce_sum(s)
    
grad = tape.gradient(loss, s)

In [11]:
[var.name for var in tape.watched_variables()]


[]

In [5]:
inputs = keras.Input(shape=(1,))
outputs = layers.Dense(10)(inputs)

model = keras.Model(inputs=inputs, outputs=outputs)

In [6]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense_1 (Dense)             (None, 10)                20        
                                                                 
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [ ]:
"""
Deep Q-Network Q(a, s)
-----------------------
TD Learning, Off-Policy, e-Greedy Exploration (GLIE).

Q(S, A) <- Q(S, A) + alpha * (R + lambda * Q(newS, newA) - Q(S, A))
delta_w = R + lambda * Q(newS, newA)

See David Silver RL Tutorial Lecture 5 - Q-Learning for more details.

Reference
----------
original paper: https://storage.googleapis.com/deepmind-media/dqn/DQNNaturePaper.pdf
EN: https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0#.5m3361vlw
CN: https://zhuanlan.zhihu.com/p/25710327

Note: Policy Network has been proved to be better than Q-Learning, see tutorial_atari_pong.py

Environment
-----------
# The FrozenLake v0 environment
https://gym.openai.com/envs/FrozenLake-v0
The agent controls the movement of a character in a grid world. Some tiles of
the grid are walkable, and others lead to the agent falling into the water.
Additionally, the movement direction of the agent is uncertain and only partially
depends on the chosen direction. The agent is rewarded for finding a walkable
path to a goal tile.
SFFF       (S: starting point, safe)
FHFH       (F: frozen surface, safe)
FFFH       (H: hole, fall to your doom)
HFFG       (G: goal, where the frisbee is located)
The episode ends when you reach the goal or fall in a hole. You receive a reward
of 1 if you reach the goal, and zero otherwise.

Prerequisites
--------------
tensorflow>=2.0.0a0
tensorlayer>=2.0.0

To run
-------
python tutorial_DQN.py --train/test


"""
import argparse
import time
import gym
import numpy as np
import tensorflow as tf
import tensorlayer as tl

# add arguments in command  --train/test
# 关于argparase的应用，可以看看我这篇知乎专栏：
# 小段文讲清argparse模块基本用法[小番外]
# https://zhuanlan.zhihu.com/p/111010774
# 注意：原代码默认为test，我改为了train。
parser = argparse.ArgumentParser(
    description='Train or test neural net motor controller.')
parser.add_argument('--train', dest='train', action='store_true', default=True)
parser.add_argument('--test', dest='test', action='store_true', default=False)
args = parser.parse_args()

tl.logging.set_verbosity(tl.logging.DEBUG)

#####################  hyper parameters  ####################
lambd = .99             # 折扣率(decay factor)
e = 0.1                 # epsilon-greedy算法参数，越大随机性越大，越倾向于探索行为。
num_episodes = 10000    # 迭代次数
render = False          # 是否渲染游戏
running_reward = None

##################### DQN ##########################

## 把分类的数字表示，变成onehot表示。
# 例如有4类，那么第三类变为：[0,0,1,0]的表示。


def to_one_hot(i, n_classes=None):
    a = np.zeros(n_classes, 'uint8')    # 这里先按照分类数量构建一个全0向量
    a[i] = 1                            # 然后点亮需要onehot的位数。
    return a


## Define Q-network q(a,s) that ouput the rewards of 4 actions by given state, i.e. Action-Value Function.
# encoding for state: 4x4 grid can be represented by one-hot vector with 16 integers.
def get_model(inputs_shape):
    '''
    定义Q网络模型：
    1. 注意输入的shape和输出的shape
    2. W_init和b_init是模型在初始化的时候，控制初始化参数的随机。该代码中用正态分布，均值0，方差0.01的方式初始化参数。
    '''
    ni = tl.layers.Input(inputs_shape, name='observation')
    nn = tl.layers.Dense(4, act=None, W_init=tf.random_uniform_initializer(
        0, 0.01), b_init=None, name='q_a_s')(ni)
    return tl.models.Model(inputs=ni, outputs=nn, name="Q-Network")


def save_ckpt(model):  # save trained weights
    '''
    保存参数
    '''
    tl.files.save_npz(model.trainable_weights, name='dqn_model.npz')


def load_ckpt(model):  # load trained weights
    '''
    加载参数
    '''
    tl.files.load_and_assign_npz(name='dqn_model.npz', network=model)


if __name__ == '__main__':

    qnetwork = get_model([None, 16])  # 定义inputshape[None,16]。16是state数量
    qnetwork.train()  # 调用tensorlayer的时候，需要标注这个模型是否可以训练。(再次吐槽tenorlayers...)
    train_weights = qnetwork.trainable_weights  # 模型的参数

    optimizer = tf.optimizers.SGD(learning_rate=0.1)  # 定义优化器
    env = gym.make('FrozenLake-v0')  # 定义环境

    # ======开始训练=======
    if args.train:
        t0 = time.time()
        for i in range(num_episodes):
            ## 重置环境初始状态
            s = env.reset()
            rAll = 0
            for j in range(99):             # 最多探索99步。因为环境状态比较少，99步一般也够探索到最终状态了。
                if render:
                    env.render()

                ## 把state放入network，计算Q值。
                ## 注意，这里先把state进行onehote处理，这里注意解释下什么是onehot
                ## 输出，这个状态下，所有动作的Q值，也就是说，是一个[None,4]大小的矩阵
                allQ = qnetwork(np.asarray(
                    [to_one_hot(s, 16)], dtype=np.float32)).numpy()

                # 在矩阵中找最大的Q值的动作
                a = np.argmax(allQ, 1)

                # e-Greedy：如果小于epsilon，就智能体随机探索。否则，就用最大Q值的动作。
                if np.random.rand(1) < e:
                    a[0] = env.action_space.sample()

                # 输入到环境，获得下一步的state，reward，done
                s1, r, d, _ = env.step(a[0])

                # 把new-state 放入，预测下一个state的**所有动作**的Q值。
                Q1 = qnetwork(np.asarray(
                    [to_one_hot(s1, 16)], dtype=np.float32)).numpy()

                ##=======计算target=======
                ## 构建更新target：
                #    Q'(s,a) <- Q(s,a) + alpha(r + lambd * maxQ(s',a') - Q(s, a))
                maxQ1 = np.max(Q1)          # 下一个状态中最大Q值.
                # 用allQ(现在状态的Q值)构建更新的target。因为只有被选择那个动作才会被更新到。
                targetQ = allQ
                targetQ[0, a[0]] = r + lambd * maxQ1

                ## 利用自动求导 进行更新。
                with tf.GradientTape() as tape:
                    # 把s放入到Q网络，计算_qvalues。
                    _qvalues = qnetwork(np.asarray(
                        [to_one_hot(s, 16)], dtype=np.float32))
                    #_qvalues和targetQ的差距就是loss。这里衡量的尺子是mse
                    _loss = tl.cost.mean_squared_error(
                        targetQ, _qvalues, is_mean=False)
                # 同梯度带求导对网络参数求导
                grad = tape.gradient(_loss, train_weights)
                # 应用梯度到网络参数求导
                optimizer.apply_gradients(zip(grad, train_weights))

                # 累计reward，并且把s更新为newstate
                rAll += r
                s = s1

                #更新epsilon，让epsilon随着迭代次数增加而减少。
                #目的就是智能体越来越少进行“探索”
                if d == True:
                    e = 1. / ((i / 50) + 10)
                    break

            ## 这里的running_reward用于记载每一次更新的总和。为了能够更加看清变化，所以大部分是前面的。只有一部分是后面的。
            running_reward = rAll if running_reward is None else running_reward * 0.99 + rAll * 0.01
            # print("Episode [%d/%d] sum reward: %f running reward: %f took: %.5fs " % \
            #     (i, num_episodes, rAll, running_reward, time.time() - episode_time))
            print('Episode: {}/{}  | Episode Reward: {:.4f} | Running Average Reward: {:.4f}  | Running Time: {:.4f}'
                  .format(i, num_episodes, rAll, running_reward,  time.time()-t0))
        save_ckpt(qnetwork)  # save model

    ##============这部分是正式游戏了========
    # 这部分就不讲解了，和训练一样。只是少了epsilon-greedy。
    if args.test:
        t0 = time.time()
        load_ckpt(qnetwork)  # load model
        for i in range(num_episodes):
            ## Reset environment and get first new observation
            episode_time = time.time()
            s = env.reset()  # observation is state, integer 0 ~ 15
            rAll = 0
            for j in range(99):  # step index, maximum step is 99
                if render:
                    env.render()

                ## Choose an action by greedily (with e chance of random action) from the Q-network
                allQ = qnetwork(np.asarray(
                    [to_one_hot(s, 16)], dtype=np.float32)).numpy()
                a = np.argmax(allQ, 1)  # no epsilon, only greedy for testing

                ## Get new state and reward from environment
                s1, r, d, _ = env.step(a[0])
                rAll += r
                s = s1
                ## Reduce chance of random action if an episode is done.
                if d == True:
                    #e = 1. / ((i / 50) + 10)  # reduce e, GLIE: Greey in the limit with infinite Exploration
                    break

            ## Note that, the rewards here with random action
            running_reward = rAll if running_reward is None else running_reward * 0.99 + rAll * 0.01
            # print("Episode [%d/%d] sum reward: %f running reward: %f took: %.5fs " % \
            #     (i, num_episodes, rAll, running_reward, time.time() - episode_time))
            print('Episode: {}/{}  | Episode Reward: {:.4f} | Running Average Reward: {:.4f}  | Running Time: {:.4f}'
                  .format(i, num_episodes, rAll, running_reward,  time.time()-t0))


In [2]:
y_true = np.random.randint(0, 2, size=(2, 3))
y_pred = np.random.random(size=(2, 3))
loss = tf.keras.losses.mean_squared_error(y_true, y_pred)
assert loss.shape == (2,)
assert np.array_equal(
    loss.numpy(), np.mean(np.square(y_true - y_pred), axis=-1))


In [4]:
a = tf.zeros((6,))
c = tf.ones((2,))
b = a
c = a